apiVersion: v1
kind: Service
metadata:
  namespace: observability
  name: prometheus-api-service
spec:
  selector:
    app.kubernetes.io/name: prometheus
    prometheus: kube-prom-stack-kube-prome-prometheus
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 30090
  type: NodePort
  