apiVersion: v1
kind: Service
metadata:
  name: kube-prom-stack-nginx-ingress-microk8s
  namespace: ingress
  labels:
    microk8s-application: nginx-ingress-microk8s
    release: kube-prom-stack
spec:
  ports:
    - port: 10254
      targetPort: 10254
      name: health
      protocol: TCP
  selector:
    name: nginx-ingress-microk8s